name: infra
on:
  workflow_dispatch:
  push:
    paths: ['terraform/**']
permissions:
  id-token: write
  contents: read
jobs:
  tf-apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
      - name: Terraform Init/Plan/Apply
        working-directory: terraform
        run: |
          terraform init
          terraform fmt -recursive
          terraform validate
          terraform plan -input=false
          terraform apply -auto-approve
